services:
  cua_web:
    build: .
    container_name: cua_web
    restart: always
    env_file: .env
    ports:
      - '8002:4800'
    depends_on:
      - cua_api
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
