services:
  cua_web:
    build: .
    container_name: '${CONTAINER_PREFIX:-cua}_web'
    restart: always
    env_file: .env
    ports:
      - '${WEB_HOST_PORT:-8002}:4800'
    depends_on:
      - cua_api
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
